//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 01:54:43 PM ICT 
//


package progrss.hrcertificate.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfMT_CertificationInstitute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfMT_CertificationInstitute"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MT_CertificationInstitute" type="{http://tempuri.org/}MT_CertificationInstitute" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfMT_CertificationInstitute", propOrder = {
    "mtCertificationInstitute"
})
public class ArrayOfMTCertificationInstitute {

    @XmlElement(name = "MT_CertificationInstitute", nillable = true)
    protected List<MTCertificationInstitute> mtCertificationInstitute;

    /**
     * Gets the value of the mtCertificationInstitute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mtCertificationInstitute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMTCertificationInstitute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MTCertificationInstitute }
     * 
     * 
     */
    public List<MTCertificationInstitute> getMTCertificationInstitute() {
        if (mtCertificationInstitute == null) {
            mtCertificationInstitute = new ArrayList<MTCertificationInstitute>();
        }
        return this.mtCertificationInstitute;
    }

}
