//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.20 at 03:48:07 PM ICT 
//


package progress.hrCertification.form.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the progress.hrCertification.form.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReturnListObjectOfMTSkillType_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_SkillType");
    private final static QName _ReturnListObjectOfMTCertFocusArea_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_CertFocusArea");
    private final static QName _ReturnListObjectOfMTCertificationInstitute_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_CertificationInstitute");
    private final static QName _ReturnListObjectOfMTIncentiveLevel_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_IncentiveLevel");
    private final static QName _ReturnListObjectOfInt32_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfInt32");
    private final static QName _ReturnMessage_QNAME = new QName("http://tempuri.org/", "ReturnMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: progress.hrCertification.form.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetListSkillType }
     * 
     */
    public GetListSkillType createGetListSkillType() {
        return new GetListSkillType();
    }

    /**
     * Create an instance of {@link GetListSkillTypeResponse }
     * 
     */
    public GetListSkillTypeResponse createGetListSkillTypeResponse() {
        return new GetListSkillTypeResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTSkillType }
     * 
     */
    public ReturnListObjectOfMTSkillType createReturnListObjectOfMTSkillType() {
        return new ReturnListObjectOfMTSkillType();
    }

    /**
     * Create an instance of {@link GetListFocusArea }
     * 
     */
    public GetListFocusArea createGetListFocusArea() {
        return new GetListFocusArea();
    }

    /**
     * Create an instance of {@link GetListFocusAreaResponse }
     * 
     */
    public GetListFocusAreaResponse createGetListFocusAreaResponse() {
        return new GetListFocusAreaResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTCertFocusArea }
     * 
     */
    public ReturnListObjectOfMTCertFocusArea createReturnListObjectOfMTCertFocusArea() {
        return new ReturnListObjectOfMTCertFocusArea();
    }

    /**
     * Create an instance of {@link GetListInstituteName }
     * 
     */
    public GetListInstituteName createGetListInstituteName() {
        return new GetListInstituteName();
    }

    /**
     * Create an instance of {@link GetListInstituteNameResponse }
     * 
     */
    public GetListInstituteNameResponse createGetListInstituteNameResponse() {
        return new GetListInstituteNameResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTCertificationInstitute }
     * 
     */
    public ReturnListObjectOfMTCertificationInstitute createReturnListObjectOfMTCertificationInstitute() {
        return new ReturnListObjectOfMTCertificationInstitute();
    }

    /**
     * Create an instance of {@link GetListCertifiedLevel }
     * 
     */
    public GetListCertifiedLevel createGetListCertifiedLevel() {
        return new GetListCertifiedLevel();
    }

    /**
     * Create an instance of {@link GetListCertifiedLevelResponse }
     * 
     */
    public GetListCertifiedLevelResponse createGetListCertifiedLevelResponse() {
        return new GetListCertifiedLevelResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTIncentiveLevel }
     * 
     */
    public ReturnListObjectOfMTIncentiveLevel createReturnListObjectOfMTIncentiveLevel() {
        return new ReturnListObjectOfMTIncentiveLevel();
    }

    /**
     * Create an instance of {@link GetCertifiedYear }
     * 
     */
    public GetCertifiedYear createGetCertifiedYear() {
        return new GetCertifiedYear();
    }

    /**
     * Create an instance of {@link GetCertifiedYearResponse }
     * 
     */
    public GetCertifiedYearResponse createGetCertifiedYearResponse() {
        return new GetCertifiedYearResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfInt32 }
     * 
     */
//    public ReturnListObjectOfInt32 createReturnListObjectOfInt32() {
//        return new ReturnListObjectOfInt32();
//    }

    /**
     * Create an instance of {@link UnLockItem }
     * 
     */
    public UnLockItem createUnLockItem() {
        return new UnLockItem();
    }

    /**
     * Create an instance of {@link UnLockItemResponse }
     * 
     */
    public UnLockItemResponse createUnLockItemResponse() {
        return new UnLockItemResponse();
    }

    /**
     * Create an instance of {@link ReturnMessage }
     * 
     */
//    public ReturnMessage createReturnMessage() {
//        return new ReturnMessage();
//    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link ListEmployeeInfoCertificationFormItem }
     * 
     */
    public ListEmployeeInfoCertificationFormItem createListEmployeeInfoCertificationFormItem() {
        return new ListEmployeeInfoCertificationFormItem();
    }

    /**
     * Create an instance of {@link UpdateResponse }
     * 
     */
    public UpdateResponse createUpdateResponse() {
        return new UpdateResponse();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link ArrayOfMTSkillType }
     * 
     */
    public ArrayOfMTSkillType createArrayOfMTSkillType() {
        return new ArrayOfMTSkillType();
    }

    /**
     * Create an instance of {@link MTSkillType }
     * 
     */
    public MTSkillType createMTSkillType() {
        return new MTSkillType();
    }

    /**
     * Create an instance of {@link ArrayOfMTCertFocusArea }
     * 
     */
    public ArrayOfMTCertFocusArea createArrayOfMTCertFocusArea() {
        return new ArrayOfMTCertFocusArea();
    }

    /**
     * Create an instance of {@link MTCertFocusArea }
     * 
     */
    public MTCertFocusArea createMTCertFocusArea() {
        return new MTCertFocusArea();
    }

    /**
     * Create an instance of {@link ArrayOfMTCertificationInstitute }
     * 
     */
    public ArrayOfMTCertificationInstitute createArrayOfMTCertificationInstitute() {
        return new ArrayOfMTCertificationInstitute();
    }

    /**
     * Create an instance of {@link MTCertificationInstitute }
     * 
     */
    public MTCertificationInstitute createMTCertificationInstitute() {
        return new MTCertificationInstitute();
    }

    /**
     * Create an instance of {@link ArrayOfMTIncentiveLevel }
     * 
     */
    public ArrayOfMTIncentiveLevel createArrayOfMTIncentiveLevel() {
        return new ArrayOfMTIncentiveLevel();
    }

    /**
     * Create an instance of {@link MTIncentiveLevel }
     * 
     */
    public MTIncentiveLevel createMTIncentiveLevel() {
        return new MTIncentiveLevel();
    }

    /**
     * Create an instance of {@link ArrayOfInt }
     * 
     */
    public ArrayOfInt createArrayOfInt() {
        return new ArrayOfInt();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTSkillType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_SkillType")
    public JAXBElement<ReturnListObjectOfMTSkillType> createReturnListObjectOfMTSkillType(ReturnListObjectOfMTSkillType value) {
        return new JAXBElement<ReturnListObjectOfMTSkillType>(_ReturnListObjectOfMTSkillType_QNAME, ReturnListObjectOfMTSkillType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTCertFocusArea }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_CertFocusArea")
    public JAXBElement<ReturnListObjectOfMTCertFocusArea> createReturnListObjectOfMTCertFocusArea(ReturnListObjectOfMTCertFocusArea value) {
        return new JAXBElement<ReturnListObjectOfMTCertFocusArea>(_ReturnListObjectOfMTCertFocusArea_QNAME, ReturnListObjectOfMTCertFocusArea.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTCertificationInstitute }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_CertificationInstitute")
    public JAXBElement<ReturnListObjectOfMTCertificationInstitute> createReturnListObjectOfMTCertificationInstitute(ReturnListObjectOfMTCertificationInstitute value) {
        return new JAXBElement<ReturnListObjectOfMTCertificationInstitute>(_ReturnListObjectOfMTCertificationInstitute_QNAME, ReturnListObjectOfMTCertificationInstitute.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTIncentiveLevel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_IncentiveLevel")
    public JAXBElement<ReturnListObjectOfMTIncentiveLevel> createReturnListObjectOfMTIncentiveLevel(ReturnListObjectOfMTIncentiveLevel value) {
        return new JAXBElement<ReturnListObjectOfMTIncentiveLevel>(_ReturnListObjectOfMTIncentiveLevel_QNAME, ReturnListObjectOfMTIncentiveLevel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfInt32 }{@code >}}
     * 
     */
//    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfInt32")
//    public JAXBElement<ReturnListObjectOfInt32> createReturnListObjectOfInt32(ReturnListObjectOfInt32 value) {
//        return new JAXBElement<ReturnListObjectOfInt32>(_ReturnListObjectOfInt32_QNAME, ReturnListObjectOfInt32 .class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnMessage }{@code >}}
     * 
     */
//    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnMessage")
//    public JAXBElement<ReturnMessage> createReturnMessage(ReturnMessage value) {
//        return new JAXBElement<ReturnMessage>(_ReturnMessage_QNAME, ReturnMessage.class, null, value);
//    }

}
