//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 01:55:55 PM ICT 
//


package progrss.hrpersonal.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetItemGeneralResult" type="{http://tempuri.org/}ReturnObjectOfList_EmployeeInfo_GeneralForm" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getItemGeneralResult"
})
@XmlRootElement(name = "GetItemGeneralResponse")
public class GetItemGeneralResponse {

    @XmlElement(name = "GetItemGeneralResult")
    protected ReturnObjectOfListEmployeeInfoGeneralForm getItemGeneralResult;

    /**
     * Gets the value of the getItemGeneralResult property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnObjectOfListEmployeeInfoGeneralForm }
     *     
     */
    public ReturnObjectOfListEmployeeInfoGeneralForm getGetItemGeneralResult() {
        return getItemGeneralResult;
    }

    /**
     * Sets the value of the getItemGeneralResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnObjectOfListEmployeeInfoGeneralForm }
     *     
     */
    public void setGetItemGeneralResult(ReturnObjectOfListEmployeeInfoGeneralForm value) {
        this.getItemGeneralResult = value;
    }

}
