//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 01:55:55 PM ICT 
//


package progrss.hrpersonal.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the progrss.hrpersonal.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReturnListObjectOfMTNationality_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_Nationality");
    private final static QName _ReturnListObjectOfMTRace_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_Race");
    private final static QName _ReturnListObjectOfMTListOfValue_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_ListOfValue");
    private final static QName _ReturnListObjectOfMTBank_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_Bank");
    private final static QName _ReturnListObjectOfMTResignationCategory_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_ResignationCategory");
    private final static QName _ReturnMessage_QNAME = new QName("http://tempuri.org/", "ReturnMessage");
    private final static QName _ReturnObjectOfListEmployeeInfoGeneralForm_QNAME = new QName("http://tempuri.org/", "ReturnObjectOfList_EmployeeInfo_GeneralForm");
    private final static QName _ReturnObjectOfEmployeePersonalInfo_QNAME = new QName("http://tempuri.org/", "ReturnObjectOfEmployeePersonalInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: progrss.hrpersonal.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetListNationality }
     * 
     */
    public GetListNationality createGetListNationality() {
        return new GetListNationality();
    }

    /**
     * Create an instance of {@link GetListNationalityResponse }
     * 
     */
    public GetListNationalityResponse createGetListNationalityResponse() {
        return new GetListNationalityResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTNationality }
     * 
     */
    public ReturnListObjectOfMTNationality createReturnListObjectOfMTNationality() {
        return new ReturnListObjectOfMTNationality();
    }

    /**
     * Create an instance of {@link GetListRace }
     * 
     */
    public GetListRace createGetListRace() {
        return new GetListRace();
    }

    /**
     * Create an instance of {@link GetListRaceResponse }
     * 
     */
    public GetListRaceResponse createGetListRaceResponse() {
        return new GetListRaceResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTRace }
     * 
     */
    public ReturnListObjectOfMTRace createReturnListObjectOfMTRace() {
        return new ReturnListObjectOfMTRace();
    }

    /**
     * Create an instance of {@link GetListReligion }
     * 
     */
    public GetListReligion createGetListReligion() {
        return new GetListReligion();
    }

    /**
     * Create an instance of {@link GetListReligionResponse }
     * 
     */
    public GetListReligionResponse createGetListReligionResponse() {
        return new GetListReligionResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTListOfValue }
     * 
     */
    public ReturnListObjectOfMTListOfValue createReturnListObjectOfMTListOfValue() {
        return new ReturnListObjectOfMTListOfValue();
    }

    /**
     * Create an instance of {@link GetListBankCode }
     * 
     */
    public GetListBankCode createGetListBankCode() {
        return new GetListBankCode();
    }

    /**
     * Create an instance of {@link GetListBankCodeResponse }
     * 
     */
    public GetListBankCodeResponse createGetListBankCodeResponse() {
        return new GetListBankCodeResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTBank }
     * 
     */
    public ReturnListObjectOfMTBank createReturnListObjectOfMTBank() {
        return new ReturnListObjectOfMTBank();
    }

    /**
     * Create an instance of {@link GetListReasonOfResignation }
     * 
     */
    public GetListReasonOfResignation createGetListReasonOfResignation() {
        return new GetListReasonOfResignation();
    }

    /**
     * Create an instance of {@link GetListReasonOfResignationResponse }
     * 
     */
    public GetListReasonOfResignationResponse createGetListReasonOfResignationResponse() {
        return new GetListReasonOfResignationResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTReasonOfResignation }
     * 
     */
    public ReturnListObjectOfMTReasonOfResignation createReturnListObjectOfMTReasonOfResignation() {
        return new ReturnListObjectOfMTReasonOfResignation();
    }

    /**
     * Create an instance of {@link GetListResignationCategory }
     * 
     */
    public GetListResignationCategory createGetListResignationCategory() {
        return new GetListResignationCategory();
    }

    /**
     * Create an instance of {@link GetListResignationCategoryResponse }
     * 
     */
    public GetListResignationCategoryResponse createGetListResignationCategoryResponse() {
        return new GetListResignationCategoryResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTResignationCategory }
     * 
     */
    public ReturnListObjectOfMTResignationCategory createReturnListObjectOfMTResignationCategory() {
        return new ReturnListObjectOfMTResignationCategory();
    }

    /**
     * Create an instance of {@link GetListIDCardType }
     * 
     */
    public GetListIDCardType createGetListIDCardType() {
        return new GetListIDCardType();
    }

    /**
     * Create an instance of {@link GetListIDCardTypeResponse }
     * 
     */
    public GetListIDCardTypeResponse createGetListIDCardTypeResponse() {
        return new GetListIDCardTypeResponse();
    }

    /**
     * Create an instance of {@link Insert }
     * 
     */
    public Insert createInsert() {
        return new Insert();
    }

    /**
     * Create an instance of {@link ListEmployeePersonalInfo }
     * 
     */
    public ListEmployeePersonalInfo createListEmployeePersonalInfo() {
        return new ListEmployeePersonalInfo();
    }

    /**
     * Create an instance of {@link InsertResponse }
     * 
     */
    public InsertResponse createInsertResponse() {
        return new InsertResponse();
    }

    /**
     * Create an instance of {@link ReturnMessage }
     * 
     */
    public ReturnMessage createReturnMessage() {
        return new ReturnMessage();
    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link UpdateResponse }
     * 
     */
    public UpdateResponse createUpdateResponse() {
        return new UpdateResponse();
    }

    /**
     * Create an instance of {@link UnlockData }
     * 
     */
    public UnlockData createUnlockData() {
        return new UnlockData();
    }

    /**
     * Create an instance of {@link UnlockDataResponse }
     * 
     */
    public UnlockDataResponse createUnlockDataResponse() {
        return new UnlockDataResponse();
    }

    /**
     * Create an instance of {@link GetItemGeneral }
     * 
     */
    public GetItemGeneral createGetItemGeneral() {
        return new GetItemGeneral();
    }

    /**
     * Create an instance of {@link GetItemGeneralResponse }
     * 
     */
    public GetItemGeneralResponse createGetItemGeneralResponse() {
        return new GetItemGeneralResponse();
    }

    /**
     * Create an instance of {@link ReturnObjectOfListEmployeeInfoGeneralForm }
     * 
     */
    public ReturnObjectOfListEmployeeInfoGeneralForm createReturnObjectOfListEmployeeInfoGeneralForm() {
        return new ReturnObjectOfListEmployeeInfoGeneralForm();
    }

    /**
     * Create an instance of {@link GetListMartialStatus }
     * 
     */
    public GetListMartialStatus createGetListMartialStatus() {
        return new GetListMartialStatus();
    }

    /**
     * Create an instance of {@link GetListMartialStatusResponse }
     * 
     */
    public GetListMartialStatusResponse createGetListMartialStatusResponse() {
        return new GetListMartialStatusResponse();
    }

    /**
     * Create an instance of {@link CheckExistStaffPersonalByIDCard }
     * 
     */
    public CheckExistStaffPersonalByIDCard createCheckExistStaffPersonalByIDCard() {
        return new CheckExistStaffPersonalByIDCard();
    }

    /**
     * Create an instance of {@link CheckExistStaffPersonalByIDCardResponse }
     * 
     */
    public CheckExistStaffPersonalByIDCardResponse createCheckExistStaffPersonalByIDCardResponse() {
        return new CheckExistStaffPersonalByIDCardResponse();
    }

    /**
     * Create an instance of {@link ReturnObjectOfEmployeePersonalInfo }
     * 
     */
    public ReturnObjectOfEmployeePersonalInfo createReturnObjectOfEmployeePersonalInfo() {
        return new ReturnObjectOfEmployeePersonalInfo();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link ArrayOfMTNationality }
     * 
     */
    public ArrayOfMTNationality createArrayOfMTNationality() {
        return new ArrayOfMTNationality();
    }

    /**
     * Create an instance of {@link MTNationality }
     * 
     */
    public MTNationality createMTNationality() {
        return new MTNationality();
    }

    /**
     * Create an instance of {@link ArrayOfMTRace }
     * 
     */
    public ArrayOfMTRace createArrayOfMTRace() {
        return new ArrayOfMTRace();
    }

    /**
     * Create an instance of {@link MTRace }
     * 
     */
    public MTRace createMTRace() {
        return new MTRace();
    }

    /**
     * Create an instance of {@link ArrayOfMTListOfValue }
     * 
     */
    public ArrayOfMTListOfValue createArrayOfMTListOfValue() {
        return new ArrayOfMTListOfValue();
    }

    /**
     * Create an instance of {@link MTListOfValue }
     * 
     */
    public MTListOfValue createMTListOfValue() {
        return new MTListOfValue();
    }

    /**
     * Create an instance of {@link ArrayOfMTBank }
     * 
     */
    public ArrayOfMTBank createArrayOfMTBank() {
        return new ArrayOfMTBank();
    }

    /**
     * Create an instance of {@link MTBank }
     * 
     */
    public MTBank createMTBank() {
        return new MTBank();
    }

    /**
     * Create an instance of {@link ArrayOfMTReasonOfResignation }
     * 
     */
    public ArrayOfMTReasonOfResignation createArrayOfMTReasonOfResignation() {
        return new ArrayOfMTReasonOfResignation();
    }

    /**
     * Create an instance of {@link MTReasonOfResignation }
     * 
     */
    public MTReasonOfResignation createMTReasonOfResignation() {
        return new MTReasonOfResignation();
    }

    /**
     * Create an instance of {@link ArrayOfMTResignationCategory }
     * 
     */
    public ArrayOfMTResignationCategory createArrayOfMTResignationCategory() {
        return new ArrayOfMTResignationCategory();
    }

    /**
     * Create an instance of {@link MTResignationCategory }
     * 
     */
    public MTResignationCategory createMTResignationCategory() {
        return new MTResignationCategory();
    }

    /**
     * Create an instance of {@link ListEmployeeInfoGeneralForm }
     * 
     */
    public ListEmployeeInfoGeneralForm createListEmployeeInfoGeneralForm() {
        return new ListEmployeeInfoGeneralForm();
    }

    /**
     * Create an instance of {@link EmployeePersonalInfo }
     * 
     */
    public EmployeePersonalInfo createEmployeePersonalInfo() {
        return new EmployeePersonalInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTNationality }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_Nationality")
    public JAXBElement<ReturnListObjectOfMTNationality> createReturnListObjectOfMTNationality(ReturnListObjectOfMTNationality value) {
        return new JAXBElement<ReturnListObjectOfMTNationality>(_ReturnListObjectOfMTNationality_QNAME, ReturnListObjectOfMTNationality.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTRace }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_Race")
    public JAXBElement<ReturnListObjectOfMTRace> createReturnListObjectOfMTRace(ReturnListObjectOfMTRace value) {
        return new JAXBElement<ReturnListObjectOfMTRace>(_ReturnListObjectOfMTRace_QNAME, ReturnListObjectOfMTRace.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTListOfValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_ListOfValue")
    public JAXBElement<ReturnListObjectOfMTListOfValue> createReturnListObjectOfMTListOfValue(ReturnListObjectOfMTListOfValue value) {
        return new JAXBElement<ReturnListObjectOfMTListOfValue>(_ReturnListObjectOfMTListOfValue_QNAME, ReturnListObjectOfMTListOfValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTBank }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_Bank")
    public JAXBElement<ReturnListObjectOfMTBank> createReturnListObjectOfMTBank(ReturnListObjectOfMTBank value) {
        return new JAXBElement<ReturnListObjectOfMTBank>(_ReturnListObjectOfMTBank_QNAME, ReturnListObjectOfMTBank.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTResignationCategory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_ResignationCategory")
    public JAXBElement<ReturnListObjectOfMTResignationCategory> createReturnListObjectOfMTResignationCategory(ReturnListObjectOfMTResignationCategory value) {
        return new JAXBElement<ReturnListObjectOfMTResignationCategory>(_ReturnListObjectOfMTResignationCategory_QNAME, ReturnListObjectOfMTResignationCategory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnMessage")
    public JAXBElement<ReturnMessage> createReturnMessage(ReturnMessage value) {
        return new JAXBElement<ReturnMessage>(_ReturnMessage_QNAME, ReturnMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnObjectOfListEmployeeInfoGeneralForm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnObjectOfList_EmployeeInfo_GeneralForm")
    public JAXBElement<ReturnObjectOfListEmployeeInfoGeneralForm> createReturnObjectOfListEmployeeInfoGeneralForm(ReturnObjectOfListEmployeeInfoGeneralForm value) {
        return new JAXBElement<ReturnObjectOfListEmployeeInfoGeneralForm>(_ReturnObjectOfListEmployeeInfoGeneralForm_QNAME, ReturnObjectOfListEmployeeInfoGeneralForm.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnObjectOfEmployeePersonalInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnObjectOfEmployeePersonalInfo")
    public JAXBElement<ReturnObjectOfEmployeePersonalInfo> createReturnObjectOfEmployeePersonalInfo(ReturnObjectOfEmployeePersonalInfo value) {
        return new JAXBElement<ReturnObjectOfEmployeePersonalInfo>(_ReturnObjectOfEmployeePersonalInfo_QNAME, ReturnObjectOfEmployeePersonalInfo.class, null, value);
    }

}
