//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 06:10:37 PM ICT 
//


package progress.hrStaffWorkingInfo.form.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import progress.hrStaffGeneral.form.wsdl.ReturnListObjectOfMTOrganizationDepartment;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetListFilterTeamResult" type="{http://tempuri.org/}ReturnListObjectOfMT_OrganizationDepartment" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getListFilterTeamResult"
})
@XmlRootElement(name = "GetListFilterTeamResponse")
public class GetListFilterTeamResponse {

    @XmlElement(name = "GetListFilterTeamResult")
    protected ReturnListObjectOfMTOrganizationDepartment getListFilterTeamResult;

    /**
     * Gets the value of the getListFilterTeamResult property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnListObjectOfMTOrganizationDepartment }
     *     
     */
    public ReturnListObjectOfMTOrganizationDepartment getGetListFilterTeamResult() {
        return getListFilterTeamResult;
    }

    /**
     * Sets the value of the getListFilterTeamResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnListObjectOfMTOrganizationDepartment }
     *     
     */
    public void setGetListFilterTeamResult(ReturnListObjectOfMTOrganizationDepartment value) {
        this.getListFilterTeamResult = value;
    }

}
