//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.20 at 03:49:23 PM ICT 
//


package progress.hrStaffWorkingInfo.form.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the progress.hrStaffWorkingInfo.form.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReturnObjectOfEmployeeWorkInfo_QNAME = new QName("http://tempuri.org/", "ReturnObjectOfEmployeeWorkInfo");
    private final static QName _ReturnObjectOfListEmployeeWorkInfoForm_QNAME = new QName("http://tempuri.org/", "ReturnObjectOfList_EmployeeWorkInfo_Form");
    private final static QName _ReturnLockState_QNAME = new QName("http://tempuri.org/", "ReturnLockState");
    private final static QName _ReturnMessage_QNAME = new QName("http://tempuri.org/", "ReturnMessage");
    private final static QName _ReturnEmployeeStatus_QNAME = new QName("http://tempuri.org/", "ReturnEmployeeStatus");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: progress.hrStaffWorkingInfo.form.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetItemEmployeeWorkingInfo }
     * 
     */
    public GetItemEmployeeWorkingInfo createGetItemEmployeeWorkingInfo() {
        return new GetItemEmployeeWorkingInfo();
    }

    /**
     * Create an instance of {@link GetItemEmployeeWorkingInfoResponse }
     * 
     */
    public GetItemEmployeeWorkingInfoResponse createGetItemEmployeeWorkingInfoResponse() {
        return new GetItemEmployeeWorkingInfoResponse();
    }

    /**
     * Create an instance of {@link ReturnObjectOfEmployeeWorkInfo }
     * 
     */
//    public ReturnObjectOfEmployeeWorkInfo createReturnObjectOfEmployeeWorkInfo() {
//        return new ReturnObjectOfEmployeeWorkInfo();
//    }

    /**
     * Create an instance of {@link GetItemEmployeeWorkingInfoForm }
     * 
     */
    public GetItemEmployeeWorkingInfoForm createGetItemEmployeeWorkingInfoForm() {
        return new GetItemEmployeeWorkingInfoForm();
    }

    /**
     * Create an instance of {@link GetItemEmployeeWorkingInfoFormResponse }
     * 
     */
    public GetItemEmployeeWorkingInfoFormResponse createGetItemEmployeeWorkingInfoFormResponse() {
        return new GetItemEmployeeWorkingInfoFormResponse();
    }

    /**
     * Create an instance of {@link ReturnObjectOfListEmployeeWorkInfoForm }
     * 
     */
//    public ReturnObjectOfListEmployeeWorkInfoForm createReturnObjectOfListEmployeeWorkInfoForm() {
//        return new ReturnObjectOfListEmployeeWorkInfoForm();
//    }

    /**
     * Create an instance of {@link GetItemLockedState }
     * 
     */
    public GetItemLockedState createGetItemLockedState() {
        return new GetItemLockedState();
    }

    /**
     * Create an instance of {@link GetItemLockedStateResponse }
     * 
     */
    public GetItemLockedStateResponse createGetItemLockedStateResponse() {
        return new GetItemLockedStateResponse();
    }

    /**
     * Create an instance of {@link ReturnLockState }
     * 
     */
//    public ReturnLockState createReturnLockState() {
//        return new ReturnLockState();
//    }

    /**
     * Create an instance of {@link LockedItem }
     * 
     */
    public LockedItem createLockedItem() {
        return new LockedItem();
    }

    /**
     * Create an instance of {@link LockedItemResponse }
     * 
     */
    public LockedItemResponse createLockedItemResponse() {
        return new LockedItemResponse();
    }

    /**
     * Create an instance of {@link ReturnMessage }
     * 
     */
//    public ReturnMessage createReturnMessage() {
//        return new ReturnMessage();
//    }

    /**
     * Create an instance of {@link GetEmployeeStatus }
     * 
     */
    public GetEmployeeStatus createGetEmployeeStatus() {
        return new GetEmployeeStatus();
    }

    /**
     * Create an instance of {@link GetEmployeeStatusResponse }
     * 
     */
    public GetEmployeeStatusResponse createGetEmployeeStatusResponse() {
        return new GetEmployeeStatusResponse();
    }

    /**
     * Create an instance of {@link ReturnEmployeeStatus }
     * 
     */
//    public ReturnEmployeeStatus createReturnEmployeeStatus() {
//        return new ReturnEmployeeStatus();
//    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link EmployeeWorkInfo }
     * 
     */
    public EmployeeWorkInfo createEmployeeWorkInfo() {
        return new EmployeeWorkInfo();
    }

    /**
     * Create an instance of {@link ListEmployeeWorkInfoForm }
     * 
     */
    public ListEmployeeWorkInfoForm createListEmployeeWorkInfoForm() {
        return new ListEmployeeWorkInfoForm();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnObjectOfEmployeeWorkInfo }{@code >}}
     * 
     */
//    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnObjectOfEmployeeWorkInfo")
//    public JAXBElement<ReturnObjectOfEmployeeWorkInfo> createReturnObjectOfEmployeeWorkInfo(ReturnObjectOfEmployeeWorkInfo value) {
//        return new JAXBElement<ReturnObjectOfEmployeeWorkInfo>(_ReturnObjectOfEmployeeWorkInfo_QNAME, ReturnObjectOfEmployeeWorkInfo.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnObjectOfListEmployeeWorkInfoForm }{@code >}}
     * 
     */
//    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnObjectOfList_EmployeeWorkInfo_Form")
//    public JAXBElement<ReturnObjectOfListEmployeeWorkInfoForm> createReturnObjectOfListEmployeeWorkInfoForm(ReturnObjectOfListEmployeeWorkInfoForm value) {
//        return new JAXBElement<ReturnObjectOfListEmployeeWorkInfoForm>(_ReturnObjectOfListEmployeeWorkInfoForm_QNAME, ReturnObjectOfListEmployeeWorkInfoForm.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnLockState }{@code >}}
     * 
     */
//    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnLockState")
//    public JAXBElement<ReturnLockState> createReturnLockState(ReturnLockState value) {
//        return new JAXBElement<ReturnLockState>(_ReturnLockState_QNAME, ReturnLockState.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnMessage }{@code >}}
     * 
     */
//    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnMessage")
//    public JAXBElement<ReturnMessage> createReturnMessage(ReturnMessage value) {
//        return new JAXBElement<ReturnMessage>(_ReturnMessage_QNAME, ReturnMessage.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnEmployeeStatus }{@code >}}
     * 
     */
//    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnEmployeeStatus")
//    public JAXBElement<ReturnEmployeeStatus> createReturnEmployeeStatus(ReturnEmployeeStatus value) {
//        return new JAXBElement<ReturnEmployeeStatus>(_ReturnEmployeeStatus_QNAME, ReturnEmployeeStatus.class, null, value);
//    }

}
