//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.31 at 03:21:22 PM ICT 
//


package progress.hrStaffListInfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List_EmployeeList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="List_EmployeeList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EmployeeID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="StaffCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TitleENName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ENFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ENLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DepartmentCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DepartmentName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PositionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EmployeeTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EmployeeStatusName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ENFullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DepartmentID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="DivisionID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "List_EmployeeList", propOrder = {
    "employeeID",
    "staffCode",
    "titleENName",
    "enFirstName",
    "enLastName",
    "departmentCode",
    "departmentName",
    "positionName",
    "employeeTypeName",
    "employeeStatusName",
    "enFullName",
    "departmentID",
    "divisionID"
})
public class ListEmployeeList {

    @XmlElement(name = "EmployeeID")
    protected int employeeID;
    @XmlElement(name = "StaffCode")
    protected String staffCode;
    @XmlElement(name = "TitleENName")
    protected String titleENName;
    @XmlElement(name = "ENFirstName")
    protected String enFirstName;
    @XmlElement(name = "ENLastName")
    protected String enLastName;
    @XmlElement(name = "DepartmentCode")
    protected String departmentCode;
    @XmlElement(name = "DepartmentName")
    protected String departmentName;
    @XmlElement(name = "PositionName")
    protected String positionName;
    @XmlElement(name = "EmployeeTypeName")
    protected String employeeTypeName;
    @XmlElement(name = "EmployeeStatusName")
    protected String employeeStatusName;
    @XmlElement(name = "ENFullName")
    protected String enFullName;
    @XmlElement(name = "DepartmentID")
    protected int departmentID;
    @XmlElement(name = "DivisionID")
    protected int divisionID;

    /**
     * Gets the value of the employeeID property.
     * 
     */
    public int getEmployeeID() {
        return employeeID;
    }

    /**
     * Sets the value of the employeeID property.
     * 
     */
    public void setEmployeeID(int value) {
        this.employeeID = value;
    }

    /**
     * Gets the value of the staffCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaffCode() {
        return staffCode;
    }

    /**
     * Sets the value of the staffCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaffCode(String value) {
        this.staffCode = value;
    }

    /**
     * Gets the value of the titleENName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleENName() {
        return titleENName;
    }

    /**
     * Sets the value of the titleENName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleENName(String value) {
        this.titleENName = value;
    }

    /**
     * Gets the value of the enFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENFirstName() {
        return enFirstName;
    }

    /**
     * Sets the value of the enFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENFirstName(String value) {
        this.enFirstName = value;
    }

    /**
     * Gets the value of the enLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENLastName() {
        return enLastName;
    }

    /**
     * Sets the value of the enLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENLastName(String value) {
        this.enLastName = value;
    }

    /**
     * Gets the value of the departmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * Sets the value of the departmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentCode(String value) {
        this.departmentCode = value;
    }

    /**
     * Gets the value of the departmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * Sets the value of the departmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentName(String value) {
        this.departmentName = value;
    }

    /**
     * Gets the value of the positionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * Sets the value of the positionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionName(String value) {
        this.positionName = value;
    }

    /**
     * Gets the value of the employeeTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeTypeName() {
        return employeeTypeName;
    }

    /**
     * Sets the value of the employeeTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeTypeName(String value) {
        this.employeeTypeName = value;
    }

    /**
     * Gets the value of the employeeStatusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeStatusName() {
        return employeeStatusName;
    }

    /**
     * Sets the value of the employeeStatusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeStatusName(String value) {
        this.employeeStatusName = value;
    }

    /**
     * Gets the value of the enFullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENFullName() {
        return enFullName;
    }

    /**
     * Sets the value of the enFullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENFullName(String value) {
        this.enFullName = value;
    }

    /**
     * Gets the value of the departmentID property.
     * 
     */
    public int getDepartmentID() {
        return departmentID;
    }

    /**
     * Sets the value of the departmentID property.
     * 
     */
    public void setDepartmentID(int value) {
        this.departmentID = value;
    }

    /**
     * Gets the value of the divisionID property.
     * 
     */
    public int getDivisionID() {
        return divisionID;
    }

    /**
     * Sets the value of the divisionID property.
     * 
     */
    public void setDivisionID(int value) {
        this.divisionID = value;
    }

}
