//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.31 at 03:21:22 PM ICT 
//


package progress.hrStaffListInfo.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the progress.hrStaffListInfo.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReturnListObjectOfMTOrganizationDepartment_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_OrganizationDepartment");
    private final static QName _ReturnListObjectOfListWorkPositionInfo_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfList_WorkPositionInfo");
    private final static QName _ReturnListObjectOfListEmployeeList_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfList_EmployeeList");
    private final static QName _ReturnMessage_QNAME = new QName("http://tempuri.org/", "ReturnMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: progress.hrStaffListInfo.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetListDepartment }
     * 
     */
    public GetListDepartment createGetListDepartment() {
        return new GetListDepartment();
    }

    /**
     * Create an instance of {@link GetListDepartmentResponse }
     * 
     */
    public GetListDepartmentResponse createGetListDepartmentResponse() {
        return new GetListDepartmentResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTOrganizationDepartment }
     * 
     */
    public ReturnListObjectOfMTOrganizationDepartment createReturnListObjectOfMTOrganizationDepartment() {
        return new ReturnListObjectOfMTOrganizationDepartment();
    }

    /**
     * Create an instance of {@link GetListWorkPosition }
     * 
     */
    public GetListWorkPosition createGetListWorkPosition() {
        return new GetListWorkPosition();
    }

    /**
     * Create an instance of {@link GetListWorkPositionResponse }
     * 
     */
    public GetListWorkPositionResponse createGetListWorkPositionResponse() {
        return new GetListWorkPositionResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfListWorkPositionInfo }
     * 
     */
    public ReturnListObjectOfListWorkPositionInfo createReturnListObjectOfListWorkPositionInfo() {
        return new ReturnListObjectOfListWorkPositionInfo();
    }

    /**
     * Create an instance of {@link GetEmployeeList }
     * 
     */
    public GetEmployeeList createGetEmployeeList() {
        return new GetEmployeeList();
    }

    /**
     * Create an instance of {@link GetEmployeeListResponse }
     * 
     */
    public GetEmployeeListResponse createGetEmployeeListResponse() {
        return new GetEmployeeListResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfListEmployeeList }
     * 
     */
    public ReturnListObjectOfListEmployeeList createReturnListObjectOfListEmployeeList() {
        return new ReturnListObjectOfListEmployeeList();
    }

    /**
     * Create an instance of {@link GetListWorkPositionForDropdown }
     * 
     */
    public GetListWorkPositionForDropdown createGetListWorkPositionForDropdown() {
        return new GetListWorkPositionForDropdown();
    }

    /**
     * Create an instance of {@link GetListWorkPositionForDropdownResponse }
     * 
     */
    public GetListWorkPositionForDropdownResponse createGetListWorkPositionForDropdownResponse() {
        return new GetListWorkPositionForDropdownResponse();
    }

    /**
     * Create an instance of {@link DeleteEmployeeData }
     * 
     */
    public DeleteEmployeeData createDeleteEmployeeData() {
        return new DeleteEmployeeData();
    }

    /**
     * Create an instance of {@link DeleteEmployeeDataResponse }
     * 
     */
    public DeleteEmployeeDataResponse createDeleteEmployeeDataResponse() {
        return new DeleteEmployeeDataResponse();
    }

    /**
     * Create an instance of {@link ReturnMessage }
     * 
     */
    public ReturnMessage createReturnMessage() {
        return new ReturnMessage();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link ArrayOfMTOrganizationDepartment }
     * 
     */
    public ArrayOfMTOrganizationDepartment createArrayOfMTOrganizationDepartment() {
        return new ArrayOfMTOrganizationDepartment();
    }

    /**
     * Create an instance of {@link MTOrganizationDepartment }
     * 
     */
    public MTOrganizationDepartment createMTOrganizationDepartment() {
        return new MTOrganizationDepartment();
    }

    /**
     * Create an instance of {@link ArrayOfListWorkPositionInfo }
     * 
     */
    public ArrayOfListWorkPositionInfo createArrayOfListWorkPositionInfo() {
        return new ArrayOfListWorkPositionInfo();
    }

    /**
     * Create an instance of {@link ListWorkPositionInfo }
     * 
     */
    public ListWorkPositionInfo createListWorkPositionInfo() {
        return new ListWorkPositionInfo();
    }

    /**
     * Create an instance of {@link ArrayOfListEmployeeList }
     * 
     */
    public ArrayOfListEmployeeList createArrayOfListEmployeeList() {
        return new ArrayOfListEmployeeList();
    }

    /**
     * Create an instance of {@link ListEmployeeList }
     * 
     */
    public ListEmployeeList createListEmployeeList() {
        return new ListEmployeeList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTOrganizationDepartment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_OrganizationDepartment")
    public JAXBElement<ReturnListObjectOfMTOrganizationDepartment> createReturnListObjectOfMTOrganizationDepartment(ReturnListObjectOfMTOrganizationDepartment value) {
        return new JAXBElement<ReturnListObjectOfMTOrganizationDepartment>(_ReturnListObjectOfMTOrganizationDepartment_QNAME, ReturnListObjectOfMTOrganizationDepartment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfListWorkPositionInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfList_WorkPositionInfo")
    public JAXBElement<ReturnListObjectOfListWorkPositionInfo> createReturnListObjectOfListWorkPositionInfo(ReturnListObjectOfListWorkPositionInfo value) {
        return new JAXBElement<ReturnListObjectOfListWorkPositionInfo>(_ReturnListObjectOfListWorkPositionInfo_QNAME, ReturnListObjectOfListWorkPositionInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfListEmployeeList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfList_EmployeeList")
    public JAXBElement<ReturnListObjectOfListEmployeeList> createReturnListObjectOfListEmployeeList(ReturnListObjectOfListEmployeeList value) {
        return new JAXBElement<ReturnListObjectOfListEmployeeList>(_ReturnListObjectOfListEmployeeList_QNAME, ReturnListObjectOfListEmployeeList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnMessage")
    public JAXBElement<ReturnMessage> createReturnMessage(ReturnMessage value) {
        return new JAXBElement<ReturnMessage>(_ReturnMessage_QNAME, ReturnMessage.class, null, value);
    }

}
