//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.20 at 03:45:15 PM ICT 
//


package progress.hrStaffGeneral.form.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfList_EmployeeListWithJobLevel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfList_EmployeeListWithJobLevel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="List_EmployeeListWithJobLevel" type="{http://tempuri.org/}List_EmployeeListWithJobLevel" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfList_EmployeeListWithJobLevel", propOrder = {
    "listEmployeeListWithJobLevel"
})
public class ArrayOfListEmployeeListWithJobLevel {

    @XmlElement(name = "List_EmployeeListWithJobLevel", nillable = true)
    protected List<ListEmployeeListWithJobLevel> listEmployeeListWithJobLevel;

    /**
     * Gets the value of the listEmployeeListWithJobLevel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listEmployeeListWithJobLevel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListEmployeeListWithJobLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListEmployeeListWithJobLevel }
     * 
     * 
     */
    public List<ListEmployeeListWithJobLevel> getListEmployeeListWithJobLevel() {
        if (listEmployeeListWithJobLevel == null) {
            listEmployeeListWithJobLevel = new ArrayList<ListEmployeeListWithJobLevel>();
        }
        return this.listEmployeeListWithJobLevel;
    }

}
