//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.20 at 03:45:15 PM ICT 
//


package progress.hrStaffGeneral.form.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetItemByEmployeeIDResult" type="{http://tempuri.org/}ReturnObjectOfEmployeeInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getItemByEmployeeIDResult"
})
@XmlRootElement(name = "GetItemByEmployeeIDResponse")
public class GetItemByEmployeeIDResponse {

    @XmlElement(name = "GetItemByEmployeeIDResult")
    protected ReturnObjectOfEmployeeInfo getItemByEmployeeIDResult;

    /**
     * Gets the value of the getItemByEmployeeIDResult property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnObjectOfEmployeeInfo }
     *     
     */
    public ReturnObjectOfEmployeeInfo getGetItemByEmployeeIDResult() {
        return getItemByEmployeeIDResult;
    }

    /**
     * Sets the value of the getItemByEmployeeIDResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnObjectOfEmployeeInfo }
     *     
     */
    public void setGetItemByEmployeeIDResult(ReturnObjectOfEmployeeInfo value) {
        this.getItemByEmployeeIDResult = value;
    }

}
