//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.20 at 03:45:15 PM ICT 
//


package progress.hrStaffGeneral.form.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for List_WorkPositionInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="List_WorkPositionInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PositionID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="PositionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PositionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PositionNameAndPositionLevelCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="JobLevel" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="IsActive" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="UpdatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="UpdatedByName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UpdatedBy" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CreatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="CreatedByName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CreatedBy" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CareerGroupID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="MajorRoleID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="PositionGroupID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="PositionLevelID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CareerGroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MajorRoleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PositionGroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PositionLevelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="JobLevelName" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CareerGroupCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PositionLevelCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PositionGroupCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "List_WorkPositionInfo", propOrder = {
    "positionID",
    "positionCode",
    "positionName",
    "positionNameAndPositionLevelCode",
    "jobLevel",
    "isActive",
    "updatedDate",
    "updatedByName",
    "updatedBy",
    "createdDate",
    "createdByName",
    "createdBy",
    "careerGroupID",
    "majorRoleID",
    "positionGroupID",
    "positionLevelID",
    "careerGroupName",
    "majorRoleName",
    "positionGroupName",
    "positionLevelName",
    "jobLevelName",
    "careerGroupCode",
    "positionLevelCode",
    "positionGroupCode"
})
public class ListWorkPositionInfo {

    @XmlElement(name = "PositionID")
    protected int positionID;
    @XmlElement(name = "PositionCode")
    protected String positionCode;
    @XmlElement(name = "PositionName")
    protected String positionName;
    @XmlElement(name = "PositionNameAndPositionLevelCode")
    protected String positionNameAndPositionLevelCode;
    @XmlElement(name = "JobLevel", required = true, type = Integer.class, nillable = true)
    protected Integer jobLevel;
    @XmlElement(name = "IsActive")
    protected boolean isActive;
    @XmlElement(name = "UpdatedDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updatedDate;
    @XmlElement(name = "UpdatedByName")
    protected String updatedByName;
    @XmlElement(name = "UpdatedBy", required = true, type = Integer.class, nillable = true)
    protected Integer updatedBy;
    @XmlElement(name = "CreatedDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDate;
    @XmlElement(name = "CreatedByName")
    protected String createdByName;
    @XmlElement(name = "CreatedBy")
    protected int createdBy;
    @XmlElement(name = "CareerGroupID")
    protected int careerGroupID;
    @XmlElement(name = "MajorRoleID")
    protected int majorRoleID;
    @XmlElement(name = "PositionGroupID")
    protected int positionGroupID;
    @XmlElement(name = "PositionLevelID")
    protected int positionLevelID;
    @XmlElement(name = "CareerGroupName")
    protected String careerGroupName;
    @XmlElement(name = "MajorRoleName")
    protected String majorRoleName;
    @XmlElement(name = "PositionGroupName")
    protected String positionGroupName;
    @XmlElement(name = "PositionLevelName")
    protected String positionLevelName;
    @XmlElement(name = "JobLevelName", required = true, type = Integer.class, nillable = true)
    protected Integer jobLevelName;
    @XmlElement(name = "CareerGroupCode")
    protected String careerGroupCode;
    @XmlElement(name = "PositionLevelCode")
    protected String positionLevelCode;
    @XmlElement(name = "PositionGroupCode")
    protected String positionGroupCode;

    /**
     * Gets the value of the positionID property.
     * 
     */
    public int getPositionID() {
        return positionID;
    }

    /**
     * Sets the value of the positionID property.
     * 
     */
    public void setPositionID(int value) {
        this.positionID = value;
    }

    /**
     * Gets the value of the positionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionCode() {
        return positionCode;
    }

    /**
     * Sets the value of the positionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionCode(String value) {
        this.positionCode = value;
    }

    /**
     * Gets the value of the positionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * Sets the value of the positionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionName(String value) {
        this.positionName = value;
    }

    /**
     * Gets the value of the positionNameAndPositionLevelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionNameAndPositionLevelCode() {
        return positionNameAndPositionLevelCode;
    }

    /**
     * Sets the value of the positionNameAndPositionLevelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionNameAndPositionLevelCode(String value) {
        this.positionNameAndPositionLevelCode = value;
    }

    /**
     * Gets the value of the jobLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getJobLevel() {
        return jobLevel;
    }

    /**
     * Sets the value of the jobLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setJobLevel(Integer value) {
        this.jobLevel = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     */
    public boolean isIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     */
    public void setIsActive(boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedDate(XMLGregorianCalendar value) {
        this.updatedDate = value;
    }

    /**
     * Gets the value of the updatedByName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedByName() {
        return updatedByName;
    }

    /**
     * Sets the value of the updatedByName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedByName(String value) {
        this.updatedByName = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUpdatedBy(Integer value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the createdByName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * Sets the value of the createdByName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedByName(String value) {
        this.createdByName = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     */
    public int getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     */
    public void setCreatedBy(int value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the careerGroupID property.
     * 
     */
    public int getCareerGroupID() {
        return careerGroupID;
    }

    /**
     * Sets the value of the careerGroupID property.
     * 
     */
    public void setCareerGroupID(int value) {
        this.careerGroupID = value;
    }

    /**
     * Gets the value of the majorRoleID property.
     * 
     */
    public int getMajorRoleID() {
        return majorRoleID;
    }

    /**
     * Sets the value of the majorRoleID property.
     * 
     */
    public void setMajorRoleID(int value) {
        this.majorRoleID = value;
    }

    /**
     * Gets the value of the positionGroupID property.
     * 
     */
    public int getPositionGroupID() {
        return positionGroupID;
    }

    /**
     * Sets the value of the positionGroupID property.
     * 
     */
    public void setPositionGroupID(int value) {
        this.positionGroupID = value;
    }

    /**
     * Gets the value of the positionLevelID property.
     * 
     */
    public int getPositionLevelID() {
        return positionLevelID;
    }

    /**
     * Sets the value of the positionLevelID property.
     * 
     */
    public void setPositionLevelID(int value) {
        this.positionLevelID = value;
    }

    /**
     * Gets the value of the careerGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareerGroupName() {
        return careerGroupName;
    }

    /**
     * Sets the value of the careerGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareerGroupName(String value) {
        this.careerGroupName = value;
    }

    /**
     * Gets the value of the majorRoleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMajorRoleName() {
        return majorRoleName;
    }

    /**
     * Sets the value of the majorRoleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorRoleName(String value) {
        this.majorRoleName = value;
    }

    /**
     * Gets the value of the positionGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionGroupName() {
        return positionGroupName;
    }

    /**
     * Sets the value of the positionGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionGroupName(String value) {
        this.positionGroupName = value;
    }

    /**
     * Gets the value of the positionLevelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionLevelName() {
        return positionLevelName;
    }

    /**
     * Sets the value of the positionLevelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionLevelName(String value) {
        this.positionLevelName = value;
    }

    /**
     * Gets the value of the jobLevelName property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getJobLevelName() {
        return jobLevelName;
    }

    /**
     * Sets the value of the jobLevelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setJobLevelName(Integer value) {
        this.jobLevelName = value;
    }

    /**
     * Gets the value of the careerGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareerGroupCode() {
        return careerGroupCode;
    }

    /**
     * Sets the value of the careerGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareerGroupCode(String value) {
        this.careerGroupCode = value;
    }

    /**
     * Gets the value of the positionLevelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionLevelCode() {
        return positionLevelCode;
    }

    /**
     * Sets the value of the positionLevelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionLevelCode(String value) {
        this.positionLevelCode = value;
    }

    /**
     * Gets the value of the positionGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionGroupCode() {
        return positionGroupCode;
    }

    /**
     * Sets the value of the positionGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionGroupCode(String value) {
        this.positionGroupCode = value;
    }

}
