//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.20 at 03:45:15 PM ICT 
//


package progress.hrStaffGeneral.form.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the progress.hrStaffGeneral.form.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReturnListObjectOfMTWorkSite_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_WorkSite");
    private final static QName _ReturnListObjectOfMTListOfValue_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_ListOfValue");
    private final static QName _ReturnListObjectOfMTEmployeeType_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_EmployeeType");
    private final static QName _ReturnListObjectOfMTNameTitle_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_NameTitle");
    private final static QName _ReturnListObjectOfMTCareerGroup_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_CareerGroup");
    private final static QName _ReturnListObjectOfListWorkPositionInfo_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfList_WorkPositionInfo");
    private final static QName _ReturnListObjectOfMTOrganizationDivision_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_OrganizationDivision");
    private final static QName _ReturnListObjectOfMTOrganizationDepartment_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_OrganizationDepartment");
    private final static QName _ReturnListObjectOfMTBusinessUnit_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_BusinessUnit");
    private final static QName _ReturnListObjectOfListEmployeeListWithJobLevel_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfList_EmployeeListWithJobLevel");
    private final static QName _ReturnObjectOfEmployeeInfo_QNAME = new QName("http://tempuri.org/", "ReturnObjectOfEmployeeInfo");
    private final static QName _ReturnListObjectOfListEmployeeListApprover_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfList_EmployeeListApprover");
    private final static QName _ReturnMessage_QNAME = new QName("http://tempuri.org/", "ReturnMessage");
    private final static QName _AnyType_QNAME = new QName("http://tempuri.org/", "anyType");
    private final static QName _ReturnObjectKey_QNAME = new QName("http://tempuri.org/", "ReturnObjectKey");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: progress.hrStaffGeneral.form.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetListWokingSite }
     * 
     */
    public GetListWokingSite createGetListWokingSite() {
        return new GetListWokingSite();
    }

    /**
     * Create an instance of {@link GetListWokingSiteResponse }
     * 
     */
    public GetListWokingSiteResponse createGetListWokingSiteResponse() {
        return new GetListWokingSiteResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTWorkSite }
     * 
     */
    public ReturnListObjectOfMTWorkSite createReturnListObjectOfMTWorkSite() {
        return new ReturnListObjectOfMTWorkSite();
    }

    /**
     * Create an instance of {@link GetListEmployeeStatus }
     * 
     */
    public GetListEmployeeStatus createGetListEmployeeStatus() {
        return new GetListEmployeeStatus();
    }

    /**
     * Create an instance of {@link GetListEmployeeStatusResponse }
     * 
     */
    public GetListEmployeeStatusResponse createGetListEmployeeStatusResponse() {
        return new GetListEmployeeStatusResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTListOfValue }
     * 
     */
    public ReturnListObjectOfMTListOfValue createReturnListObjectOfMTListOfValue() {
        return new ReturnListObjectOfMTListOfValue();
    }

    /**
     * Create an instance of {@link GetListIDCardType }
     * 
     */
    public GetListIDCardType createGetListIDCardType() {
        return new GetListIDCardType();
    }

    /**
     * Create an instance of {@link GetListIDCardTypeResponse }
     * 
     */
    public GetListIDCardTypeResponse createGetListIDCardTypeResponse() {
        return new GetListIDCardTypeResponse();
    }

    /**
     * Create an instance of {@link GetListStaffType }
     * 
     */
    public GetListStaffType createGetListStaffType() {
        return new GetListStaffType();
    }

    /**
     * Create an instance of {@link GetListStaffTypeResponse }
     * 
     */
    public GetListStaffTypeResponse createGetListStaffTypeResponse() {
        return new GetListStaffTypeResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTEmployeeType }
     * 
     */
    public ReturnListObjectOfMTEmployeeType createReturnListObjectOfMTEmployeeType() {
        return new ReturnListObjectOfMTEmployeeType();
    }

    /**
     * Create an instance of {@link GetListGender }
     * 
     */
    public GetListGender createGetListGender() {
        return new GetListGender();
    }

    /**
     * Create an instance of {@link GetListGenderResponse }
     * 
     */
    public GetListGenderResponse createGetListGenderResponse() {
        return new GetListGenderResponse();
    }

    /**
     * Create an instance of {@link GetListMaritalStatus }
     * 
     */
    public GetListMaritalStatus createGetListMaritalStatus() {
        return new GetListMaritalStatus();
    }

    /**
     * Create an instance of {@link GetListMaritalStatusResponse }
     * 
     */
    public GetListMaritalStatusResponse createGetListMaritalStatusResponse() {
        return new GetListMaritalStatusResponse();
    }

    /**
     * Create an instance of {@link GetListTitleName }
     * 
     */
    public GetListTitleName createGetListTitleName() {
        return new GetListTitleName();
    }

    /**
     * Create an instance of {@link GetListTitleNameResponse }
     * 
     */
    public GetListTitleNameResponse createGetListTitleNameResponse() {
        return new GetListTitleNameResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTNameTitle }
     * 
     */
    public ReturnListObjectOfMTNameTitle createReturnListObjectOfMTNameTitle() {
        return new ReturnListObjectOfMTNameTitle();
    }

    /**
     * Create an instance of {@link GetListCareerGroup }
     * 
     */
    public GetListCareerGroup createGetListCareerGroup() {
        return new GetListCareerGroup();
    }

    /**
     * Create an instance of {@link GetListCareerGroupResponse }
     * 
     */
    public GetListCareerGroupResponse createGetListCareerGroupResponse() {
        return new GetListCareerGroupResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTCareerGroup }
     * 
     */
    public ReturnListObjectOfMTCareerGroup createReturnListObjectOfMTCareerGroup() {
        return new ReturnListObjectOfMTCareerGroup();
    }

    /**
     * Create an instance of {@link GetListWorkPosition }
     * 
     */
    public GetListWorkPosition createGetListWorkPosition() {
        return new GetListWorkPosition();
    }

    /**
     * Create an instance of {@link GetListWorkPositionResponse }
     * 
     */
    public GetListWorkPositionResponse createGetListWorkPositionResponse() {
        return new GetListWorkPositionResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfListWorkPositionInfo }
     * 
     */
    public ReturnListObjectOfListWorkPositionInfo createReturnListObjectOfListWorkPositionInfo() {
        return new ReturnListObjectOfListWorkPositionInfo();
    }

    /**
     * Create an instance of {@link GetListDivision }
     * 
     */
    public GetListDivision createGetListDivision() {
        return new GetListDivision();
    }

    /**
     * Create an instance of {@link GetListDivisionResponse }
     * 
     */
    public GetListDivisionResponse createGetListDivisionResponse() {
        return new GetListDivisionResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTOrganizationDivision }
     * 
     */
    public ReturnListObjectOfMTOrganizationDivision createReturnListObjectOfMTOrganizationDivision() {
        return new ReturnListObjectOfMTOrganizationDivision();
    }

    /**
     * Create an instance of {@link GetListDepartment }
     * 
     */
    public GetListDepartment createGetListDepartment() {
        return new GetListDepartment();
    }

    /**
     * Create an instance of {@link GetListDepartmentResponse }
     * 
     */
    public GetListDepartmentResponse createGetListDepartmentResponse() {
        return new GetListDepartmentResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTOrganizationDepartment }
     * 
     */
    public ReturnListObjectOfMTOrganizationDepartment createReturnListObjectOfMTOrganizationDepartment() {
        return new ReturnListObjectOfMTOrganizationDepartment();
    }

    /**
     * Create an instance of {@link GetListSection }
     * 
     */
    public GetListSection createGetListSection() {
        return new GetListSection();
    }

    /**
     * Create an instance of {@link GetListSectionResponse }
     * 
     */
    public GetListSectionResponse createGetListSectionResponse() {
        return new GetListSectionResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTBusinessUnit }
     * 
     */
    public ReturnListObjectOfMTBusinessUnit createReturnListObjectOfMTBusinessUnit() {
        return new ReturnListObjectOfMTBusinessUnit();
    }

    /**
     * Create an instance of {@link GetListEmployeeWithJobLevel }
     * 
     */
    public GetListEmployeeWithJobLevel createGetListEmployeeWithJobLevel() {
        return new GetListEmployeeWithJobLevel();
    }

    /**
     * Create an instance of {@link GetListEmployeeWithJobLevelResponse }
     * 
     */
    public GetListEmployeeWithJobLevelResponse createGetListEmployeeWithJobLevelResponse() {
        return new GetListEmployeeWithJobLevelResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfListEmployeeListWithJobLevel }
     * 
     */
    public ReturnListObjectOfListEmployeeListWithJobLevel createReturnListObjectOfListEmployeeListWithJobLevel() {
        return new ReturnListObjectOfListEmployeeListWithJobLevel();
    }

    /**
     * Create an instance of {@link GetItemByEmployeeID }
     * 
     */
    public GetItemByEmployeeID createGetItemByEmployeeID() {
        return new GetItemByEmployeeID();
    }

    /**
     * Create an instance of {@link GetItemByEmployeeIDResponse }
     * 
     */
    public GetItemByEmployeeIDResponse createGetItemByEmployeeIDResponse() {
        return new GetItemByEmployeeIDResponse();
    }

    /**
     * Create an instance of {@link ReturnObjectOfEmployeeInfo }
     * 
     */
    public ReturnObjectOfEmployeeInfo createReturnObjectOfEmployeeInfo() {
        return new ReturnObjectOfEmployeeInfo();
    }

    /**
     * Create an instance of {@link CheckExistStaffInfoByName }
     * 
     */
    public CheckExistStaffInfoByName createCheckExistStaffInfoByName() {
        return new CheckExistStaffInfoByName();
    }

    /**
     * Create an instance of {@link CheckExistStaffInfoByNameResponse }
     * 
     */
    public CheckExistStaffInfoByNameResponse createCheckExistStaffInfoByNameResponse() {
        return new CheckExistStaffInfoByNameResponse();
    }

    /**
     * Create an instance of {@link GetListEmployeeForTrainingApprover }
     * 
     */
    public GetListEmployeeForTrainingApprover createGetListEmployeeForTrainingApprover() {
        return new GetListEmployeeForTrainingApprover();
    }

    /**
     * Create an instance of {@link GetListEmployeeForTrainingApproverResponse }
     * 
     */
    public GetListEmployeeForTrainingApproverResponse createGetListEmployeeForTrainingApproverResponse() {
        return new GetListEmployeeForTrainingApproverResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfListEmployeeListApprover }
     * 
     */
    public ReturnListObjectOfListEmployeeListApprover createReturnListObjectOfListEmployeeListApprover() {
        return new ReturnListObjectOfListEmployeeListApprover();
    }

    /**
     * Create an instance of {@link GetListEmployeeForCertApprover }
     * 
     */
    public GetListEmployeeForCertApprover createGetListEmployeeForCertApprover() {
        return new GetListEmployeeForCertApprover();
    }

    /**
     * Create an instance of {@link GetListEmployeeForCertApproverResponse }
     * 
     */
    public GetListEmployeeForCertApproverResponse createGetListEmployeeForCertApproverResponse() {
        return new GetListEmployeeForCertApproverResponse();
    }

    /**
     * Create an instance of {@link UnLockItem }
     * 
     */
    public UnLockItem createUnLockItem() {
        return new UnLockItem();
    }

    /**
     * Create an instance of {@link UnLockItemResponse }
     * 
     */
    public UnLockItemResponse createUnLockItemResponse() {
        return new UnLockItemResponse();
    }

//    /**
//     * Create an instance of {@link ReturnMessage }
//     * 
//     */
//    public ReturnMessage createReturnMessage() {
//        return new ReturnMessage();
//    }

    /**
     * Create an instance of {@link Insert }
     * 
     */
    public Insert createInsert() {
        return new Insert();
    }

    /**
     * Create an instance of {@link ListEmployeeInfoGeneralForm }
     * 
     */
    public ListEmployeeInfoGeneralForm createListEmployeeInfoGeneralForm() {
        return new ListEmployeeInfoGeneralForm();
    }

    /**
     * Create an instance of {@link InsertResponse }
     * 
     */
    public InsertResponse createInsertResponse() {
        return new InsertResponse();
    }

    /**
     * Create an instance of {@link ReturnObjectKey }
     * 
     */
    public ReturnObjectKey createReturnObjectKey() {
        return new ReturnObjectKey();
    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link UpdateResponse }
     * 
     */
    public UpdateResponse createUpdateResponse() {
        return new UpdateResponse();
    }

    /**
     * Create an instance of {@link CheckDupWithStaffCode }
     * 
     */
    public CheckDupWithStaffCode createCheckDupWithStaffCode() {
        return new CheckDupWithStaffCode();
    }

    /**
     * Create an instance of {@link CheckDupWithStaffCodeResponse }
     * 
     */
    public CheckDupWithStaffCodeResponse createCheckDupWithStaffCodeResponse() {
        return new CheckDupWithStaffCodeResponse();
    }

    /**
     * Create an instance of {@link GetUserByStaffCode }
     * 
     */
    public GetUserByStaffCode createGetUserByStaffCode() {
        return new GetUserByStaffCode();
    }

    /**
     * Create an instance of {@link GetUserByStaffCodeResponse }
     * 
     */
    public GetUserByStaffCodeResponse createGetUserByStaffCodeResponse() {
        return new GetUserByStaffCodeResponse();
    }

    /**
     * Create an instance of {@link InsertRehireWithExistData }
     * 
     */
    public InsertRehireWithExistData createInsertRehireWithExistData() {
        return new InsertRehireWithExistData();
    }

    /**
     * Create an instance of {@link InsertRehireWithExistDataResponse }
     * 
     */
    public InsertRehireWithExistDataResponse createInsertRehireWithExistDataResponse() {
        return new InsertRehireWithExistDataResponse();
    }

    /**
     * Create an instance of {@link InsertRehireWithNewData }
     * 
     */
    public InsertRehireWithNewData createInsertRehireWithNewData() {
        return new InsertRehireWithNewData();
    }

    /**
     * Create an instance of {@link InsertRehireWithNewDataResponse }
     * 
     */
    public InsertRehireWithNewDataResponse createInsertRehireWithNewDataResponse() {
        return new InsertRehireWithNewDataResponse();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link ArrayOfMTWorkSite }
     * 
     */
    public ArrayOfMTWorkSite createArrayOfMTWorkSite() {
        return new ArrayOfMTWorkSite();
    }

    /**
     * Create an instance of {@link MTWorkSite }
     * 
     */
    public MTWorkSite createMTWorkSite() {
        return new MTWorkSite();
    }

    /**
     * Create an instance of {@link ArrayOfMTListOfValue }
     * 
     */
    public ArrayOfMTListOfValue createArrayOfMTListOfValue() {
        return new ArrayOfMTListOfValue();
    }

    /**
     * Create an instance of {@link MTListOfValue }
     * 
     */
    public MTListOfValue createMTListOfValue() {
        return new MTListOfValue();
    }

    /**
     * Create an instance of {@link ArrayOfMTEmployeeType }
     * 
     */
    public ArrayOfMTEmployeeType createArrayOfMTEmployeeType() {
        return new ArrayOfMTEmployeeType();
    }

    /**
     * Create an instance of {@link MTEmployeeType }
     * 
     */
    public MTEmployeeType createMTEmployeeType() {
        return new MTEmployeeType();
    }

    /**
     * Create an instance of {@link ArrayOfMTNameTitle }
     * 
     */
    public ArrayOfMTNameTitle createArrayOfMTNameTitle() {
        return new ArrayOfMTNameTitle();
    }

    /**
     * Create an instance of {@link MTNameTitle }
     * 
     */
    public MTNameTitle createMTNameTitle() {
        return new MTNameTitle();
    }

    /**
     * Create an instance of {@link ArrayOfMTCareerGroup }
     * 
     */
    public ArrayOfMTCareerGroup createArrayOfMTCareerGroup() {
        return new ArrayOfMTCareerGroup();
    }

    /**
     * Create an instance of {@link MTCareerGroup }
     * 
     */
    public MTCareerGroup createMTCareerGroup() {
        return new MTCareerGroup();
    }

    /**
     * Create an instance of {@link ArrayOfListWorkPositionInfo }
     * 
     */
    public ArrayOfListWorkPositionInfo createArrayOfListWorkPositionInfo() {
        return new ArrayOfListWorkPositionInfo();
    }

    /**
     * Create an instance of {@link ListWorkPositionInfo }
     * 
     */
    public ListWorkPositionInfo createListWorkPositionInfo() {
        return new ListWorkPositionInfo();
    }

    /**
     * Create an instance of {@link ArrayOfMTOrganizationDivision }
     * 
     */
    public ArrayOfMTOrganizationDivision createArrayOfMTOrganizationDivision() {
        return new ArrayOfMTOrganizationDivision();
    }

    /**
     * Create an instance of {@link MTOrganizationDivision }
     * 
     */
    public MTOrganizationDivision createMTOrganizationDivision() {
        return new MTOrganizationDivision();
    }

    /**
     * Create an instance of {@link ArrayOfMTOrganizationDepartment }
     * 
     */
    public ArrayOfMTOrganizationDepartment createArrayOfMTOrganizationDepartment() {
        return new ArrayOfMTOrganizationDepartment();
    }

    /**
     * Create an instance of {@link MTOrganizationDepartment }
     * 
     */
    public MTOrganizationDepartment createMTOrganizationDepartment() {
        return new MTOrganizationDepartment();
    }

    /**
     * Create an instance of {@link ArrayOfMTBusinessUnit }
     * 
     */
    public ArrayOfMTBusinessUnit createArrayOfMTBusinessUnit() {
        return new ArrayOfMTBusinessUnit();
    }

    /**
     * Create an instance of {@link MTBusinessUnit }
     * 
     */
    public MTBusinessUnit createMTBusinessUnit() {
        return new MTBusinessUnit();
    }

    /**
     * Create an instance of {@link ArrayOfListEmployeeListWithJobLevel }
     * 
     */
    public ArrayOfListEmployeeListWithJobLevel createArrayOfListEmployeeListWithJobLevel() {
        return new ArrayOfListEmployeeListWithJobLevel();
    }

    /**
     * Create an instance of {@link ListEmployeeListWithJobLevel }
     * 
     */
    public ListEmployeeListWithJobLevel createListEmployeeListWithJobLevel() {
        return new ListEmployeeListWithJobLevel();
    }

    /**
     * Create an instance of {@link EmployeeInfo }
     * 
     */
    public EmployeeInfo createEmployeeInfo() {
        return new EmployeeInfo();
    }

    /**
     * Create an instance of {@link ArrayOfListEmployeeListApprover }
     * 
     */
    public ArrayOfListEmployeeListApprover createArrayOfListEmployeeListApprover() {
        return new ArrayOfListEmployeeListApprover();
    }

    /**
     * Create an instance of {@link ListEmployeeListApprover }
     * 
     */
    public ListEmployeeListApprover createListEmployeeListApprover() {
        return new ListEmployeeListApprover();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTWorkSite }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_WorkSite")
    public JAXBElement<ReturnListObjectOfMTWorkSite> createReturnListObjectOfMTWorkSite(ReturnListObjectOfMTWorkSite value) {
        return new JAXBElement<ReturnListObjectOfMTWorkSite>(_ReturnListObjectOfMTWorkSite_QNAME, ReturnListObjectOfMTWorkSite.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTListOfValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_ListOfValue")
    public JAXBElement<ReturnListObjectOfMTListOfValue> createReturnListObjectOfMTListOfValue(ReturnListObjectOfMTListOfValue value) {
        return new JAXBElement<ReturnListObjectOfMTListOfValue>(_ReturnListObjectOfMTListOfValue_QNAME, ReturnListObjectOfMTListOfValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTEmployeeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_EmployeeType")
    public JAXBElement<ReturnListObjectOfMTEmployeeType> createReturnListObjectOfMTEmployeeType(ReturnListObjectOfMTEmployeeType value) {
        return new JAXBElement<ReturnListObjectOfMTEmployeeType>(_ReturnListObjectOfMTEmployeeType_QNAME, ReturnListObjectOfMTEmployeeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTNameTitle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_NameTitle")
    public JAXBElement<ReturnListObjectOfMTNameTitle> createReturnListObjectOfMTNameTitle(ReturnListObjectOfMTNameTitle value) {
        return new JAXBElement<ReturnListObjectOfMTNameTitle>(_ReturnListObjectOfMTNameTitle_QNAME, ReturnListObjectOfMTNameTitle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTCareerGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_CareerGroup")
    public JAXBElement<ReturnListObjectOfMTCareerGroup> createReturnListObjectOfMTCareerGroup(ReturnListObjectOfMTCareerGroup value) {
        return new JAXBElement<ReturnListObjectOfMTCareerGroup>(_ReturnListObjectOfMTCareerGroup_QNAME, ReturnListObjectOfMTCareerGroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfListWorkPositionInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfList_WorkPositionInfo")
    public JAXBElement<ReturnListObjectOfListWorkPositionInfo> createReturnListObjectOfListWorkPositionInfo(ReturnListObjectOfListWorkPositionInfo value) {
        return new JAXBElement<ReturnListObjectOfListWorkPositionInfo>(_ReturnListObjectOfListWorkPositionInfo_QNAME, ReturnListObjectOfListWorkPositionInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTOrganizationDivision }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_OrganizationDivision")
    public JAXBElement<ReturnListObjectOfMTOrganizationDivision> createReturnListObjectOfMTOrganizationDivision(ReturnListObjectOfMTOrganizationDivision value) {
        return new JAXBElement<ReturnListObjectOfMTOrganizationDivision>(_ReturnListObjectOfMTOrganizationDivision_QNAME, ReturnListObjectOfMTOrganizationDivision.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTOrganizationDepartment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_OrganizationDepartment")
    public JAXBElement<ReturnListObjectOfMTOrganizationDepartment> createReturnListObjectOfMTOrganizationDepartment(ReturnListObjectOfMTOrganizationDepartment value) {
        return new JAXBElement<ReturnListObjectOfMTOrganizationDepartment>(_ReturnListObjectOfMTOrganizationDepartment_QNAME, ReturnListObjectOfMTOrganizationDepartment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTBusinessUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_BusinessUnit")
    public JAXBElement<ReturnListObjectOfMTBusinessUnit> createReturnListObjectOfMTBusinessUnit(ReturnListObjectOfMTBusinessUnit value) {
        return new JAXBElement<ReturnListObjectOfMTBusinessUnit>(_ReturnListObjectOfMTBusinessUnit_QNAME, ReturnListObjectOfMTBusinessUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfListEmployeeListWithJobLevel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfList_EmployeeListWithJobLevel")
    public JAXBElement<ReturnListObjectOfListEmployeeListWithJobLevel> createReturnListObjectOfListEmployeeListWithJobLevel(ReturnListObjectOfListEmployeeListWithJobLevel value) {
        return new JAXBElement<ReturnListObjectOfListEmployeeListWithJobLevel>(_ReturnListObjectOfListEmployeeListWithJobLevel_QNAME, ReturnListObjectOfListEmployeeListWithJobLevel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnObjectOfEmployeeInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnObjectOfEmployeeInfo")
    public JAXBElement<ReturnObjectOfEmployeeInfo> createReturnObjectOfEmployeeInfo(ReturnObjectOfEmployeeInfo value) {
        return new JAXBElement<ReturnObjectOfEmployeeInfo>(_ReturnObjectOfEmployeeInfo_QNAME, ReturnObjectOfEmployeeInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfListEmployeeListApprover }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfList_EmployeeListApprover")
    public JAXBElement<ReturnListObjectOfListEmployeeListApprover> createReturnListObjectOfListEmployeeListApprover(ReturnListObjectOfListEmployeeListApprover value) {
        return new JAXBElement<ReturnListObjectOfListEmployeeListApprover>(_ReturnListObjectOfListEmployeeListApprover_QNAME, ReturnListObjectOfListEmployeeListApprover.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnMessage }{@code >}}
     * 
     */
//    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnMessage")
//    public JAXBElement<ReturnMessage> createReturnMessage(ReturnMessage value) {
//        return new JAXBElement<ReturnMessage>(_ReturnMessage_QNAME, ReturnMessage.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "anyType")
    public JAXBElement<Object> createAnyType(Object value) {
        return new JAXBElement<Object>(_AnyType_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnObjectKey }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnObjectKey")
    public JAXBElement<ReturnObjectKey> createReturnObjectKey(ReturnObjectKey value) {
        return new JAXBElement<ReturnObjectKey>(_ReturnObjectKey_QNAME, ReturnObjectKey.class, null, value);
    }

}
