//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 12:41:20 PM ICT 
//


package progress.hrsso.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetCurrentRoleUIDResult" type="{http://tempuri.org/}ResultListOfInt32" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getCurrentRoleUIDResult"
})
@XmlRootElement(name = "GetCurrentRoleUIDResponse")
public class GetCurrentRoleUIDResponse {

    @XmlElement(name = "GetCurrentRoleUIDResult")
    protected ResultListOfInt32 getCurrentRoleUIDResult;

    /**
     * Gets the value of the getCurrentRoleUIDResult property.
     * 
     * @return
     *     possible object is
     *     {@link ResultListOfInt32 }
     *     
     */
    public ResultListOfInt32 getGetCurrentRoleUIDResult() {
        return getCurrentRoleUIDResult;
    }

    /**
     * Sets the value of the getCurrentRoleUIDResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultListOfInt32 }
     *     
     */
    public void setGetCurrentRoleUIDResult(ResultListOfInt32 value) {
        this.getCurrentRoleUIDResult = value;
    }

}
