//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 12:41:20 PM ICT 
//


package progress.hrsso.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResultObjectOfvPEMS_SPStaffProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultObjectOfvPEMS_SPStaffProfile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://tempuri.org/}Result"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Object" type="{http://tempuri.org/}vPEMS_SPStaffProfile" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultObjectOfvPEMS_SPStaffProfile", propOrder = {
    "object"
})
public class ResultObjectOfvPEMSSPStaffProfile
    extends Result
{

    @XmlElement(name = "Object")
    protected VPEMSSPStaffProfile object;

    /**
     * Gets the value of the object property.
     * 
     * @return
     *     possible object is
     *     {@link VPEMSSPStaffProfile }
     *     
     */
    public VPEMSSPStaffProfile getObject() {
        return object;
    }

    /**
     * Sets the value of the object property.
     * 
     * @param value
     *     allowed object is
     *     {@link VPEMSSPStaffProfile }
     *     
     */
    public void setObject(VPEMSSPStaffProfile value) {
        this.object = value;
    }

}
