//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 12:41:20 PM ICT 
//


package progress.hrsso.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for vPEMS_SPStaffProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vPEMS_SPStaffProfile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EmployeeID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="StaffCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CitizenIDNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ThaiPrefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ThaiName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ThaiSurname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EnglishPrefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EnglishName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EnglishSurname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Sex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="EffectiveDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ResignDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="WorkingPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HomeAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HomePhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MobilePhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProbationEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="EndContractDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsDeleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="StaffProfileID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="DepartmentCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DepartmentID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="StaffPositionID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="PositionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PositionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vPEMS_SPStaffProfile", propOrder = {
    "employeeID",
    "staffCode",
    "citizenIDNumber",
    "thaiPrefix",
    "thaiName",
    "thaiSurname",
    "englishPrefix",
    "englishName",
    "englishSurname",
    "sex",
    "birthDate",
    "effectiveDate",
    "resignDate",
    "workingPhoneNumber",
    "email",
    "homeAddress",
    "homePhoneNumber",
    "mobilePhoneNumber",
    "probationEndDate",
    "endContractDate",
    "userName",
    "isDeleted",
    "staffProfileID",
    "departmentCode",
    "departmentID",
    "staffPositionID",
    "positionCode",
    "positionName"
})
public class VPEMSSPStaffProfile {

    @XmlElement(name = "EmployeeID")
    protected int employeeID;
    @XmlElement(name = "StaffCode")
    protected String staffCode;
    @XmlElement(name = "CitizenIDNumber")
    protected String citizenIDNumber;
    @XmlElement(name = "ThaiPrefix")
    protected String thaiPrefix;
    @XmlElement(name = "ThaiName")
    protected String thaiName;
    @XmlElement(name = "ThaiSurname")
    protected String thaiSurname;
    @XmlElement(name = "EnglishPrefix")
    protected String englishPrefix;
    @XmlElement(name = "EnglishName")
    protected String englishName;
    @XmlElement(name = "EnglishSurname")
    protected String englishSurname;
    @XmlElement(name = "Sex")
    protected String sex;
    @XmlElement(name = "BirthDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(name = "EffectiveDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar effectiveDate;
    @XmlElement(name = "ResignDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar resignDate;
    @XmlElement(name = "WorkingPhoneNumber")
    protected String workingPhoneNumber;
    @XmlElement(name = "Email")
    protected String email;
    @XmlElement(name = "HomeAddress")
    protected String homeAddress;
    @XmlElement(name = "HomePhoneNumber")
    protected String homePhoneNumber;
    @XmlElement(name = "MobilePhoneNumber")
    protected String mobilePhoneNumber;
    @XmlElement(name = "ProbationEndDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar probationEndDate;
    @XmlElement(name = "EndContractDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endContractDate;
    @XmlElement(name = "UserName")
    protected String userName;
    @XmlElement(name = "IsDeleted", required = true, type = Boolean.class, nillable = true)
    protected Boolean isDeleted;
    @XmlElement(name = "StaffProfileID", required = true)
    protected String staffProfileID;
    @XmlElement(name = "DepartmentCode")
    protected String departmentCode;
    @XmlElement(name = "DepartmentID", required = true)
    protected String departmentID;
    @XmlElement(name = "StaffPositionID")
    protected int staffPositionID;
    @XmlElement(name = "PositionCode")
    protected String positionCode;
    @XmlElement(name = "PositionName")
    protected String positionName;

    /**
     * Gets the value of the employeeID property.
     * 
     */
    public int getEmployeeID() {
        return employeeID;
    }

    /**
     * Sets the value of the employeeID property.
     * 
     */
    public void setEmployeeID(int value) {
        this.employeeID = value;
    }

    /**
     * Gets the value of the staffCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaffCode() {
        return staffCode;
    }

    /**
     * Sets the value of the staffCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaffCode(String value) {
        this.staffCode = value;
    }

    /**
     * Gets the value of the citizenIDNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitizenIDNumber() {
        return citizenIDNumber;
    }

    /**
     * Sets the value of the citizenIDNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitizenIDNumber(String value) {
        this.citizenIDNumber = value;
    }

    /**
     * Gets the value of the thaiPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThaiPrefix() {
        return thaiPrefix;
    }

    /**
     * Sets the value of the thaiPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThaiPrefix(String value) {
        this.thaiPrefix = value;
    }

    /**
     * Gets the value of the thaiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThaiName() {
        return thaiName;
    }

    /**
     * Sets the value of the thaiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThaiName(String value) {
        this.thaiName = value;
    }

    /**
     * Gets the value of the thaiSurname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThaiSurname() {
        return thaiSurname;
    }

    /**
     * Sets the value of the thaiSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThaiSurname(String value) {
        this.thaiSurname = value;
    }

    /**
     * Gets the value of the englishPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnglishPrefix() {
        return englishPrefix;
    }

    /**
     * Sets the value of the englishPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnglishPrefix(String value) {
        this.englishPrefix = value;
    }

    /**
     * Gets the value of the englishName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * Sets the value of the englishName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnglishName(String value) {
        this.englishName = value;
    }

    /**
     * Gets the value of the englishSurname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnglishSurname() {
        return englishSurname;
    }

    /**
     * Sets the value of the englishSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnglishSurname(String value) {
        this.englishSurname = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSex(String value) {
        this.sex = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the resignDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getResignDate() {
        return resignDate;
    }

    /**
     * Sets the value of the resignDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setResignDate(XMLGregorianCalendar value) {
        this.resignDate = value;
    }

    /**
     * Gets the value of the workingPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkingPhoneNumber() {
        return workingPhoneNumber;
    }

    /**
     * Sets the value of the workingPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkingPhoneNumber(String value) {
        this.workingPhoneNumber = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the homeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * Sets the value of the homeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeAddress(String value) {
        this.homeAddress = value;
    }

    /**
     * Gets the value of the homePhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomePhoneNumber() {
        return homePhoneNumber;
    }

    /**
     * Sets the value of the homePhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomePhoneNumber(String value) {
        this.homePhoneNumber = value;
    }

    /**
     * Gets the value of the mobilePhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilePhoneNumber() {
        return mobilePhoneNumber;
    }

    /**
     * Sets the value of the mobilePhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilePhoneNumber(String value) {
        this.mobilePhoneNumber = value;
    }

    /**
     * Gets the value of the probationEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProbationEndDate() {
        return probationEndDate;
    }

    /**
     * Sets the value of the probationEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProbationEndDate(XMLGregorianCalendar value) {
        this.probationEndDate = value;
    }

    /**
     * Gets the value of the endContractDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndContractDate() {
        return endContractDate;
    }

    /**
     * Sets the value of the endContractDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndContractDate(XMLGregorianCalendar value) {
        this.endContractDate = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the isDeleted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDeleted() {
        return isDeleted;
    }

    /**
     * Sets the value of the isDeleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDeleted(Boolean value) {
        this.isDeleted = value;
    }

    /**
     * Gets the value of the staffProfileID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaffProfileID() {
        return staffProfileID;
    }

    /**
     * Sets the value of the staffProfileID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaffProfileID(String value) {
        this.staffProfileID = value;
    }

    /**
     * Gets the value of the departmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * Sets the value of the departmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentCode(String value) {
        this.departmentCode = value;
    }

    /**
     * Gets the value of the departmentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentID() {
        return departmentID;
    }

    /**
     * Sets the value of the departmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentID(String value) {
        this.departmentID = value;
    }

    /**
     * Gets the value of the staffPositionID property.
     * 
     */
    public int getStaffPositionID() {
        return staffPositionID;
    }

    /**
     * Sets the value of the staffPositionID property.
     * 
     */
    public void setStaffPositionID(int value) {
        this.staffPositionID = value;
    }

    /**
     * Gets the value of the positionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionCode() {
        return positionCode;
    }

    /**
     * Sets the value of the positionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionCode(String value) {
        this.positionCode = value;
    }

    /**
     * Gets the value of the positionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * Sets the value of the positionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionName(String value) {
        this.positionName = value;
    }

	@Override
	public String toString() {
		return "VPEMSSPStaffProfile [employeeID=" + employeeID + ", staffCode="
				+ staffCode + ", citizenIDNumber=" + citizenIDNumber
				+ ", thaiPrefix=" + thaiPrefix + ", thaiName=" + thaiName
				+ ", thaiSurname=" + thaiSurname + ", englishPrefix="
				+ englishPrefix + ", englishName=" + englishName
				+ ", englishSurname=" + englishSurname + ", sex=" + sex
				+ ", birthDate=" + birthDate + ", effectiveDate="
				+ effectiveDate + ", resignDate=" + resignDate
				+ ", workingPhoneNumber=" + workingPhoneNumber + ", email="
				+ email + ", homeAddress=" + homeAddress + ", homePhoneNumber="
				+ homePhoneNumber + ", mobilePhoneNumber=" + mobilePhoneNumber
				+ ", probationEndDate=" + probationEndDate
				+ ", endContractDate=" + endContractDate + ", userName="
				+ userName + ", isDeleted=" + isDeleted + ", staffProfileID="
				+ staffProfileID + ", departmentCode=" + departmentCode
				+ ", departmentID=" + departmentID + ", staffPositionID="
				+ staffPositionID + ", positionCode=" + positionCode
				+ ", positionName=" + positionName + "]";
	}

    
    
}
