//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.20 at 01:52:57 PM ICT 
//


package progress.hrEmployeeInfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="getWaitForApproveCountResult" type="{http://tempuri.org/}ReturnListObjectOfInt32" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getWaitForApproveCountResult"
})
@XmlRootElement(name = "getWaitForApproveCountResponse")
public class GetWaitForApproveCountResponse {

    protected ReturnListObjectOfInt32 getWaitForApproveCountResult;

    /**
     * Gets the value of the getWaitForApproveCountResult property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnListObjectOfInt32 }
     *     
     */
    public ReturnListObjectOfInt32 getGetWaitForApproveCountResult() {
        return getWaitForApproveCountResult;
    }

    /**
     * Sets the value of the getWaitForApproveCountResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnListObjectOfInt32 }
     *     
     */
    public void setGetWaitForApproveCountResult(ReturnListObjectOfInt32 value) {
        this.getWaitForApproveCountResult = value;
    }

}
