//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 01:53:31 PM ICT 
//


package progrss.hreducation.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfList_EducationInstituteInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfList_EducationInstituteInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="List_EducationInstituteInfo" type="{http://tempuri.org/}List_EducationInstituteInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfList_EducationInstituteInfo", propOrder = {
    "listEducationInstituteInfo"
})
public class ArrayOfListEducationInstituteInfo {

    @XmlElement(name = "List_EducationInstituteInfo", nillable = true)
    protected List<ListEducationInstituteInfo> listEducationInstituteInfo;

    /**
     * Gets the value of the listEducationInstituteInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listEducationInstituteInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListEducationInstituteInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListEducationInstituteInfo }
     * 
     * 
     */
    public List<ListEducationInstituteInfo> getListEducationInstituteInfo() {
        if (listEducationInstituteInfo == null) {
            listEducationInstituteInfo = new ArrayList<ListEducationInstituteInfo>();
        }
        return this.listEducationInstituteInfo;
    }

}
