//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 01:53:31 PM ICT 
//


package progrss.hreducation.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the progrss.hreducation.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReturnListObjectOfInt32_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfInt32");
    private final static QName _ReturnListObjectOfMTListOfValue_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_ListOfValue");
    private final static QName _ReturnListObjectOfListEducationInstituteInfo_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfList_EducationInstituteInfo");
    private final static QName _ReturnListObjectOfMTCountry_QNAME = new QName("http://tempuri.org/", "ReturnListObjectOfMT_Country");
    private final static QName _ReturnMessage_QNAME = new QName("http://tempuri.org/", "ReturnMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: progrss.hreducation.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetListLongYear }
     * 
     */
    public GetListLongYear createGetListLongYear() {
        return new GetListLongYear();
    }

    /**
     * Create an instance of {@link GetListLongYearResponse }
     * 
     */
    public GetListLongYearResponse createGetListLongYearResponse() {
        return new GetListLongYearResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfInt32 }
     * 
     */
    public ReturnListObjectOfInt32 createReturnListObjectOfInt32() {
        return new ReturnListObjectOfInt32();
    }

    /**
     * Create an instance of {@link GetListDegree }
     * 
     */
    public GetListDegree createGetListDegree() {
        return new GetListDegree();
    }

    /**
     * Create an instance of {@link GetListDegreeResponse }
     * 
     */
    public GetListDegreeResponse createGetListDegreeResponse() {
        return new GetListDegreeResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTListOfValue }
     * 
     */
    public ReturnListObjectOfMTListOfValue createReturnListObjectOfMTListOfValue() {
        return new ReturnListObjectOfMTListOfValue();
    }

    /**
     * Create an instance of {@link GetListInstituteName }
     * 
     */
    public GetListInstituteName createGetListInstituteName() {
        return new GetListInstituteName();
    }

    /**
     * Create an instance of {@link GetListInstituteNameResponse }
     * 
     */
    public GetListInstituteNameResponse createGetListInstituteNameResponse() {
        return new GetListInstituteNameResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfListEducationInstituteInfo }
     * 
     */
    public ReturnListObjectOfListEducationInstituteInfo createReturnListObjectOfListEducationInstituteInfo() {
        return new ReturnListObjectOfListEducationInstituteInfo();
    }

    /**
     * Create an instance of {@link GetListCountry }
     * 
     */
    public GetListCountry createGetListCountry() {
        return new GetListCountry();
    }

    /**
     * Create an instance of {@link GetListCountryResponse }
     * 
     */
    public GetListCountryResponse createGetListCountryResponse() {
        return new GetListCountryResponse();
    }

    /**
     * Create an instance of {@link ReturnListObjectOfMTCountry }
     * 
     */
    public ReturnListObjectOfMTCountry createReturnListObjectOfMTCountry() {
        return new ReturnListObjectOfMTCountry();
    }

    /**
     * Create an instance of {@link UnLockItem }
     * 
     */
    public UnLockItem createUnLockItem() {
        return new UnLockItem();
    }

    /**
     * Create an instance of {@link UnLockItemResponse }
     * 
     */
    public UnLockItemResponse createUnLockItemResponse() {
        return new UnLockItemResponse();
    }

    /**
     * Create an instance of {@link ReturnMessage }
     * 
     */
    public ReturnMessage createReturnMessage() {
        return new ReturnMessage();
    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link ListEmployeeInfoEducationFormItem }
     * 
     */
    public ListEmployeeInfoEducationFormItem createListEmployeeInfoEducationFormItem() {
        return new ListEmployeeInfoEducationFormItem();
    }

    /**
     * Create an instance of {@link UpdateResponse }
     * 
     */
    public UpdateResponse createUpdateResponse() {
        return new UpdateResponse();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link ArrayOfInt }
     * 
     */
    public ArrayOfInt createArrayOfInt() {
        return new ArrayOfInt();
    }

    /**
     * Create an instance of {@link ArrayOfMTListOfValue }
     * 
     */
    public ArrayOfMTListOfValue createArrayOfMTListOfValue() {
        return new ArrayOfMTListOfValue();
    }

    /**
     * Create an instance of {@link MTListOfValue }
     * 
     */
    public MTListOfValue createMTListOfValue() {
        return new MTListOfValue();
    }

    /**
     * Create an instance of {@link ArrayOfListEducationInstituteInfo }
     * 
     */
    public ArrayOfListEducationInstituteInfo createArrayOfListEducationInstituteInfo() {
        return new ArrayOfListEducationInstituteInfo();
    }

    /**
     * Create an instance of {@link ListEducationInstituteInfo }
     * 
     */
    public ListEducationInstituteInfo createListEducationInstituteInfo() {
        return new ListEducationInstituteInfo();
    }

    /**
     * Create an instance of {@link ArrayOfMTCountry }
     * 
     */
    public ArrayOfMTCountry createArrayOfMTCountry() {
        return new ArrayOfMTCountry();
    }

    /**
     * Create an instance of {@link MTCountry }
     * 
     */
    public MTCountry createMTCountry() {
        return new MTCountry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfInt32 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfInt32")
    public JAXBElement<ReturnListObjectOfInt32> createReturnListObjectOfInt32(ReturnListObjectOfInt32 value) {
        return new JAXBElement<ReturnListObjectOfInt32>(_ReturnListObjectOfInt32_QNAME, ReturnListObjectOfInt32 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTListOfValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_ListOfValue")
    public JAXBElement<ReturnListObjectOfMTListOfValue> createReturnListObjectOfMTListOfValue(ReturnListObjectOfMTListOfValue value) {
        return new JAXBElement<ReturnListObjectOfMTListOfValue>(_ReturnListObjectOfMTListOfValue_QNAME, ReturnListObjectOfMTListOfValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfListEducationInstituteInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfList_EducationInstituteInfo")
    public JAXBElement<ReturnListObjectOfListEducationInstituteInfo> createReturnListObjectOfListEducationInstituteInfo(ReturnListObjectOfListEducationInstituteInfo value) {
        return new JAXBElement<ReturnListObjectOfListEducationInstituteInfo>(_ReturnListObjectOfListEducationInstituteInfo_QNAME, ReturnListObjectOfListEducationInstituteInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnListObjectOfMTCountry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnListObjectOfMT_Country")
    public JAXBElement<ReturnListObjectOfMTCountry> createReturnListObjectOfMTCountry(ReturnListObjectOfMTCountry value) {
        return new JAXBElement<ReturnListObjectOfMTCountry>(_ReturnListObjectOfMTCountry_QNAME, ReturnListObjectOfMTCountry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ReturnMessage")
    public JAXBElement<ReturnMessage> createReturnMessage(ReturnMessage value) {
        return new JAXBElement<ReturnMessage>(_ReturnMessage_QNAME, ReturnMessage.class, null, value);
    }

}
