//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 12:50:31 PM ICT 
//


package progress.hrinfo.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetListDepartmentResult" type="{http://tempuri.org/}ReturnListObjectOfMT_OrganizationDepartment" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getListDepartmentResult"
})
@XmlRootElement(name = "GetListDepartmentResponse")
public class GetListDepartmentResponse {

    @XmlElement(name = "GetListDepartmentResult")
    protected ReturnListObjectOfMTOrganizationDepartment getListDepartmentResult;

    /**
     * Gets the value of the getListDepartmentResult property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnListObjectOfMTOrganizationDepartment }
     *     
     */
    public ReturnListObjectOfMTOrganizationDepartment getGetListDepartmentResult() {
        return getListDepartmentResult;
    }

    /**
     * Sets the value of the getListDepartmentResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnListObjectOfMTOrganizationDepartment }
     *     
     */
    public void setGetListDepartmentResult(ReturnListObjectOfMTOrganizationDepartment value) {
        this.getListDepartmentResult = value;
    }

}
